CREATE DATABASE [Sandbox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sandbox', FILENAME = N'C:\XTBP10ClassFiles\Data\DBFiles\Sandbox.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sandbox_log', FILENAME = N'C:\XTBP10ClassFiles\Data\DBFiles\Sandbox_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Sandbox] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Sandbox] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Sandbox] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Sandbox] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Sandbox] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Sandbox] SET ARITHABORT OFF 
GO
ALTER DATABASE [Sandbox] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Sandbox] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Sandbox] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Sandbox] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Sandbox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Sandbox] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Sandbox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Sandbox] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Sandbox] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Sandbox] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Sandbox] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Sandbox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Sandbox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Sandbox] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Sandbox] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Sandbox] SET  READ_WRITE 
GO
ALTER DATABASE [Sandbox] SET RECOVERY FULL 
GO
ALTER DATABASE [Sandbox] SET  MULTI_USER 
GO
ALTER DATABASE [Sandbox] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Sandbox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Sandbox] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Sandbox]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Sandbox]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Sandbox] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

CREATE TABLE dbo.TempTable (hello VARCHAR(25));